### ISSUE TITLE
scopes based on cookies?

### ISSUE THREAD

**Issue by niccolox** [BartOtten/routex#10]
interesting project

could I write a scope that matches on cookies and directs to different paths?

https://bartotten.github.io/routex/Routex.Extension.Alternatives.html

**Comment by BartOtten** [comment]
Hi Niccolox,

Thanks. I am not sure I understand your question/use case. Could you please elaborate? Some options:

1. I want a route such as `/autodetect` which redirects users to `/en_US` or `/nl_NL` based on a cookie value.
2. I want to route users from `/some/:each_possible_cookie_value/path` to other routes based on the cookie value
3. other.....

**Comment by BartOtten** [comment]
Hi niccolox, as Routex 0.3.0 now supports process dictionary, this should be straightforward. However, I still miss the use case. Do notice that once a user is put in a branch (formerly called 'scope') each verified route is directly rewritten to keep the user in that branch.

I advise to offer the user options to switch scope. The example app code will be updated this week.

**Comment by BartOtten** [comment]
For now, I will close this ticket. Please let me know if you need further assistance.
